#!/usr/bin/env python
import sys
from cli.cli import CLIParser

if __name__ == '__main__':
    # if len(sys.argv) > 1 and sys.argv[1] == 'gui':
        # #load gui
        # exit()
    # else:
    p = CLIParser()
    p.parse()

